name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, test/code-review]

jobs:
  GPT-CODE-REVIEW:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
